### ISSUE TITLE
Issue #1: Dependency on file system

### ISSUE THREAD

**Issue by cjmcgraw** [Maleus/Enumerator#1]
Hey guys!

I will talk a little bit about some convention first. Then I will go into what I think should be changed. 

---
## Convention

First in programming we try to define unchanging constants in a different format than variables. So you'll see variables often in snake case `my_var` and constants in all caps `THE_VAR`.

We should try to refrain from having constants in the code in literal terms. This means no:

``` python
def increase(x):
    return x + 1

for x in range(10):
    print("Current number is :" + str(x))
```

should instead be expressed as:

``` python
INCREASE_VALUE = 1
CURR_NUM_MSG = "Current number is:"

def increase(x):
    return x + INCREASE_VALUE

for x in range(10):
    print(CURR_NUM_MSG + str(x))
```

Now the print statement might be a bit overkill. But the idea is we want to replace all `magic numbers` (weird arbitrary data just hanging out) with constants such that we don't repeat ourselves.

When it comes time to change how much we increase by we can change the INCREASE_VALUE. 

Now my examples are very bland. You normally wouldn't go this overkill, so don't feel compelled to replace EVERY literal with a constant. But if you find yourself referring to the same literals all the time. Try replacing them with a constant.

Now onto the meat of this issue then
# 
# Issue: File system dependency

Ok so I decided to pick the first issue that I think needs to be resolved is a complete dependency on an OS's specific file structure. Let me give you an example of what I mean:

You have the following code:

``` python
os.system("mkdir /root/Desktop/"+IP)
```

Inside of that code you have the string `"/root/Desktop/" + IP`

This relies heavily on three things:
1. The user having a *nix like desktop (thus the file separator is '/')
2. The user having a dir named `Desktop` in his `root`
3. Reliance on `mkdir` which is a *nix based command
4. The user having root access (may be unavoidable in the end)
5. References to the same things repeated throughout code

The best solution, in my mind would be the following steps:
- When stringing together directories use the built in `os.path.join` method. This will utilize the correct file separator for the specific file system.
  
  ``` python
  OUTPUT_DIRECTORY = os.path.join("root", "Desktop", IP)
  ```
- Remove root from the equation and reference directly to the `HOME` of the user. If the user is root, it will print out there anyways. You can reference the home
  
  ``` python
  HOME = os.environ['HOME']
  OUTPUT_DIRECTORY = os.path.join(HOME, "Desktop", IP)
  ```
- We have the following line of code (Altered to fit my new scheme):
  
  ``` python
  os.system("mkdir " + OUTPUT_DIRECTORY) 
  ```
  
  This is another dependency on `mkdir` as a command for *nix. So we can change this to be less hard coded if we utilize a specific library command in python
  
  Specifically `os.mkdir`
  
  ``` python
  os.mkdir(OUTPUT_DIRECTORY)
  ```
  
  Allows us to avoid directly referencing the *nix system. It will be independent of the OS then. Furthermore we can take another step and utilize `mkdir -R` by another python library command
  
  ``` python
  os.makedirs(OUTPUT_DIRECTORY)
  ```
  
  This change will prevent us from running into a potential issue where some user, for some reason, doesn't have a home or "Desktop" file, etc by recursively creating them all
- Root access (atleast at this point) hasn't been necessary. Since we point to home it will use /root/Desktop/{IP} for root, /home/carl/Desktop/{IP} for carl.. etc
- Now we utilize the constants I created in the code to replace some of the references for commands
  
  an example of one command change could be:
  
  ``` python
      os.system("xterm -hold -e dirb http://"+IP+" -o /root/Desktop/"+IP+"/dirb_info.txt &")
  ```
  
  to:
  
  ``` python
  #somewhere in the constants
  DIRB_INFO_FILE = os.path.join(OUTPUT_DIRECTORY, 'dirb_info.txt')
  
  os.system("xterm -hold -e dirb http://" + IP + " -o " + DIRB_INFO_FILE + " &")
  ```

While I know at the end it isn't as attractive as it could be, it is definitely an improvement and given other potential changes we could eliminate all strings in these lines and eventually encapsulate the command somewhere else.

That is when we start cooking.

**Comment by stevecoward** [comment]
Good writeup on all this! Beat me to it hehe.

**Comment by Maleus** [comment]
Addressed this issue, used your recommendations
