### ISSUE TITLE
Issue #5: D.R.Y off this code! (Its too WET!)

### ISSUE THREAD

**Issue by cjmcgraw** [Maleus/Enumerator#5]
I will briefly talk about some convention involving DRY and WET:
# 
# Convention

The programmers mantra. Every day you must get up, kneel on your desk chair, bow your head to your _CPU_ and recite it. 

> 01010100 01101111 01100100 01100001 01111001 00100000 01100001 01101100 01101100 00100000 01110100 01101000 01101001 01101110 01100111 01110011 00100000 01001001 00100000 01110100 01101111 01110101 01100011 01101000 00100000 01110111 01101001 01101100 01101100 00100000 01100010 01100101 00100000 01000100 01010010 01011001 00101100 00100000 01001001 00100000 01110011 01101000 01110101 01101110 00100000 01100001 01101100 01101100 00100000 01010111 01000101 01010100 01101110 01100101 01110011 01110011

Or in ASCII:

> Today all things I touch will be DRY, I shun all WETness

What does it mean to be DRY?

The word DRY or D.R.Y comes from the term [Don't Repeat Yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). It is the programmers creed that they will eliminate redundancy (thus maximizing laziness). 

This is contrasted by the WET or W.E.T principle which comes from the term Write Everything Twice (seeing as DRY is the opposite of WET).

Every time you repeat yourself the DRY gods frown, Every time you eliminate redundancy you make a step closer to being the perfect programmer. 

Well.. maybe.

You get the idea. Eliminating redundancy is the programmers job.

The general method of eliminating redundancy is via `encapsulation`. We `encapsulate` functionality in functions, functions in classes, classes in packages, packages in projects, etc, etc..

All of this is to stop repeating ourselves. 

This line of code:

``` python

my_data[first][second] += 5
my_data[first][second] += 2
```

Makes the DRY gods unhappy. They wish you to `encapsulate`! At the very sight of redundancy a programmer can feel the ire of the DRY gods.

He quickly encapsulates:

``` python

def update_data(n):
    my_data[first][second] += n

update_data(5)
update_data(2)
```

Thus you've evaded their wrath. For now.

Every programmer should feel uncomfortable when repeating themselves. 
# 
# Issue

There is much redundancy here. It offends my delicate sensibilities! 

The main offender however is this statement:

``` python

if nm[host].has_tcp(21) and nm[IP]['tcp'][21]['state'] == 'open':
    print "*" * 10
    print "FTP Found - Checking for anonymous access."
    ftp()
if nm[host].has_tcp(80) and nm[IP]['tcp'][80]['state'] == 'open':
    dirb()
if nm[host].has_tcp(443) and nm[IP]['tcp'][443]['state'] == 'open':
    dirb_https()
if nm[host].has_tcp(80) and nm[IP]['tcp'][80]['state'] == 'open':
    nikto()
if nm[host].has_tcp(443) and nm[IP]['tcp'][443]['state'] == 'open':
    nikto_https()
if nm[host].has_tcp(139) and nm[IP]['tcp'][139]['state'] == 'open' or nm[host].has_tcp(445) and nm[IP]['tcp'][445]['state'] == 'open': 
    enum4linux()
```

With simple encapsulation this could be reduced greatly:

``` python
if has_open_protocol(21):
    # ftp code
if has_open_protocol(80):
    # http code
if has_open_protocol(443):
    # https code
if has_open_protocol(139) or has_open_protocol(445):
    # enum4linux

def has_open_protocol(port_num):
    return nm[host].has_tcp(port_num) and nm[IP]['tcp'][port_num]['start'] == open
```

But even that might be too much repetition for the gods of DRY. There is a better way though..

**Comment by Maleus** [comment]
Attempted to fix these issues
